feat: event notifications
decentraland/events pull request #656
Opened 2024-03-25 19:40 UTC by lauti7

2024-03-26 12:23 UTC, marianogoldman requested changes

2024-03-26 12:23 UTC, marianogoldman commented on src/api/Notifications.ts
> +      eventKey: `${id}-${address}`,
I think this should be just the id. Each notification is unique by combination of `eventKey`, `type` and `address` (all three combined together).

2024-03-26 12:23 UTC, marianogoldman commented on src/api/Notifications.ts
> +        title: "Event starts in an hour",
```suggestion
        title: "Event starts in an hour.",
```

2024-03-26 12:23 UTC, marianogoldman commented on src/api/Notifications.ts
> +        description: `The event ${name} starts in an hour`,
```suggestion
        description: `The event ${name} starts in an hour.`,
```

2024-03-26 12:23 UTC, marianogoldman commented on src/api/Notifications.ts
> +      eventKey: `${id}-${address}`,
Same here.

2024-03-26 12:23 UTC, marianogoldman commented on src/entities/Event/cron.ts
> +    for (const attendee of attendees) {
We should do this differently I think, much more efficiently (like the code that is being removed). We should build an array with all the notifications and then make a simple call to the Notification Service endpoint with the whole batch.

2024-03-26 12:23 UTC, marianogoldman commented on src/entities/Event/cron.ts
> +    for (const attendee of attendees) {
Same here. Build the batch and send all notifications with a single API call.

2024-03-26 12:23 UTC, marianogoldman commented on src/entities/Event/model.ts
> +        AND e.next_start_at > (now() + interval '1 minutes')
```suggestion
        AND e.next_start_at >= (now() + interval '1 minutes')
```

2024-03-26 12:23 UTC, marianogoldman commented on src/entities/Event/model.ts
>          AND e.next_start_at > now()
```suggestion
        AND e.next_start_at >= now()
```

2024-03-26 12:23 UTC, marianogoldman commented on src/entities/Event/routes/index.ts
> -  router.post(
Do we currently have any calls to this endpoint? Removing it will break any existing client calling this.

2024-03-26 12:23 UTC, marianogoldman commented on src/entities/EventAttendee/routes.ts
> -  router.patch(
Same with this.

2024-03-27 17:51 UTC, lauti7 commented on src/entities/Event/routes/index.ts
> -  router.post(
I think we don't have. This was a testing endpoint to test push notifications for a single event that the creators could use when creating an event. Push notifications haven't been in use for a long while now.

2024-03-27 17:53 UTC, lauti7 commented on src/entities/EventAttendee/routes.ts
> -  router.patch(
This endpoint was in charge of changing the "notify" status for an attendee (if the attendee wants to receive a push notification or not). Since we deprecated push notifications a long time ago and removed the "notify" field from the database, it makes no sense to keep this endpoint.

2024-03-28 15:02 UTC, braianj requested changes

2024-03-28 15:02 UTC, braianj commented on src/entities/NotificationCursors/model.ts
> +      "getLastUpdateForNotificationType",
same here, snake case

2024-03-28 15:02 UTC, braianj commented on src/migrations/1711379513170_cursors-table.ts
> +/* eslint-disable @typescript-eslint/naming-convention */
please remove this

2024-03-28 15:02 UTC, braianj commented on src/migrations/1711139490099_delete-notify-field.ts
> +/* eslint-disable @typescript-eslint/naming-convention */
please remove this

2024-03-28 15:08 UTC, braianj approved these changes

2024-03-28 15:34 UTC, lauti7 commented on src/api/Notifications.ts
> +    `https://notifications-processor.decentraland.io`
we do this on the rest of dapps/services, .io is corpo dev environment

2024-03-28 15:39 UTC, lauti7 commented on src/api/Notifications.ts
> +        description: `The event ${event.name} starts in an hour.`,
why would we add it to translations? it's not related to i18n

2024-03-28 15:45 UTC, marianogoldman approved these changes

2024-03-28 15:55 UTC, merged